name: Deploy Blog API

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  deployments: write
  checks: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o blog_api_linux
          mkdir -p release
          cp blog_api_linux release/
          cp config/config.yaml release/
          tar -czf blog_api.tar.gz release/

      - name: Delete existing release
        uses: actions/github-script@v6
        with:
          script: |
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const release = releases.data.find(release => release.tag_name === "${{ github.ref_name }}");
            if (release) {
              await github.rest.repos.deleteRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: release.id
              });
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: blog_api.tar.gz
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            cd /opt/blog_api
            wget -q --show-progress https://github.com/${{ github.repository }}/releases/latest/download/blog_api.tar.gz
            tar xzf blog_api.tar.gz --overwrite
            chmod +x blog_api_linux
            sudo systemctl restart blog-api